### ISSUE TITLE
Game Over overlay does not force keyboard focus to only button

### ISSUE THREAD

**Issue by itsthejoker** [Janell-Huyck/2048-game#10]
When on the Game Over screen, there's only one button to click (or press) and ideally I should be able to either:

* press ESC to exit the overlay
* press Space to accept the button

However, ESC does nothing in this context and in order to properly hit the button, you need to press Tab once and then Space.

**Comment by Janell-Huyck** [comment]
Thank you for the feedback and suggestions.  I have included your fixes in this PR:
https://github.com/Janell-Huyck/2048-game/pull/11
