### ISSUE TITLE
Overlays don't disable interaction beneath them

### ISSUE THREAD

**Issue by itsthejoker** [Janell-Huyck/2048-game#9]
Nice work on this! While testing, I ran into an issue where keyboard navigation works underneath the current overlay, meaning you can start, play, and end a game underneath the help overlay.

![image](https://github.com/Janell-Huyck/2048-game/assets/5179553/0742d930-961c-43f7-9a39-f7c87788effb)

Ideally, the overlay should only allow interaction with its specific layer.

**Comment by Janell-Huyck** [comment]
Thank you for the feedback and suggestions.  I have included your fixes in this PR:
https://github.com/Janell-Huyck/2048-game/pull/11
